// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJSPYuaWHLp665Wm-mbaIv-EXc0VcTtWk',
    appId: '1:611115376000:web:2ee92caf4721bef3e27565',
    messagingSenderId: '611115376000',
    projectId: 'music-board-2024',
    authDomain: 'music-board-2024.firebaseapp.com',
    storageBucket: 'music-board-2024.firebasestorage.app',
    measurementId: 'G-9K5HE7X4H5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJSPYuaWHLp665Wm-mbaIv-EXc0VcTtWk',
    appId: '1:611115376000:web:3ca1f14c20d5094ae27565',
    messagingSenderId: '611115376000',
    projectId: 'music-board-2024',
    authDomain: 'music-board-2024.firebaseapp.com',
    storageBucket: 'music-board-2024.firebasestorage.app',
    measurementId: 'G-YNJKVH3NR2',
  );
}
